apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-serverless
  namespace: openshift-serverless
spec:
  destination:
    name: ""
    namespace: ""
    server: ""
  project: openshift-serverless
  source:
    path: docs/gitops/serverless
    repoURL: https://github.com/pierDipi/serverless-operator
    targetRevision: filter-eventing-ns-argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
